// src/config/furniture.ts

// --- FIZIKAI TULAJDONSÁGOK ---

export const ComponentType = {
  CORPUS: 'corpuses',
  FRONT: 'fronts',
  HANDLE: 'handles',
  LEG: 'legs',
  SHELF: 'shelves',
  DRAWER: 'drawers',
  OTHER: 'others',
} as const

export type ComponentType = (typeof ComponentType)[keyof typeof ComponentType]

export const FurnitureCategory = {
  BOTTOM_CABINET: 'bottom_cabinets',
  TOP_CABINET: 'top_cabinets',
  TALL_CABINET: 'tall_cabinets',
  LEG: 'legs',
  WORKTOP: 'worktops',
} as const

export type FurnitureCategory = (typeof FurnitureCategory)[keyof typeof FurnitureCategory]

export const GlobalGroupTarget = {
  WORKTOP: 'worktops',
  LEG: 'legs',
  LEG_SLOT: 'leg_slot',
  FRONT: 'fronts',
  DRAWER: 'drawers',
} as const

export type GlobalGroupTarget = (typeof GlobalGroupTarget)[keyof typeof GlobalGroupTarget]

export const ProceduralConstants = {
  LEG_STANDARD_ID: 'leg_standard',
  MESH_PLINTH: 'ProceduralPlinth',
  MESH_WORKTOP: 'ProceduralWorktop',
} as const

export interface ComponentProperties {
  width?: number
  height?: number
  depth?: number
  weight?: number
  price?: number
  wallThickness?: number // Falvastagság (mm) - FONTOS a polc matekhoz!
  maxShelves?: number // Max polc szám - FONTOS a korláthoz!
  sideDepth?: number
}

// --- CSATLAKOZÁSI PONT ---
export interface AttachmentPoint {
  id: string
  allowedComponentTypes: string[]
}

// --- KOMPONENS DEFINÍCIÓ ---
export interface ComponentConfig {
  id: string
  name: string
  price?: number
  componentType: string
  category?: string
  styleId?: string
  model: string

  materialTarget?: string
  materialSource?: string
  materialOptions?: string[]
  materialSlots?: MaterialSlotDef[]
  attachmentPoints?: AttachmentPoint[]
  allowedMaterialCategories?: string[]

  properties?: ComponentProperties
}

// ÚJ INTERFACE A POLC BEÁLLÍTÁSOKHOZ
export interface ShelfSchemaConfig {
  mode: 'auto' | 'custom' // 'auto' = Matek, 'custom' = Attach Point
  count: number // Hány darab polc (csak auto módnál)
  componentId: string | null // Milyen polcot rakjunk be (csak auto módnál)
}

export interface PropertyConfig {
  id: string
  label: string
  type: 'select' | 'checkbox' | 'number'
  options?: { label: string; value: string | number }[]
  defaultValue: string | number | boolean
  // És bármi más, ami egy property-hez kellhet
  [key: string]: string | number | boolean | undefined | { label: string; value: string | number }[]
}

export interface ComponentSlotConfig {
  slotId: string
  name: string
  componentType: string
  defaultComponent: string | null
  allowedComponents: string[]
  attachToSlot?: string
  useAttachmentPoint?: string
  attachmentMapping?: Record<string, string[]>
  position?: {
    x: number
    y: number
    z: number
  }
  rotation?: {
    x: number
    y: number
    z: number
  }
  scale?: {
    x: number
    y: number
    z: number
  }
  properties?: PropertyConfig[]
  isOptional?: boolean
  isAutoGenerated?: boolean
  children?: ComponentSlotConfig[]
}

export interface Schema {
  id: string
  name: string
  type?: 'front' | 'shelf' | 'drawer' | 'leg' | 'internal' // NEW: Schema type for filtering
  apply: Record<string, string | null> // path -> componentId
  slotProperties?: Record<string, Partial<ComponentSlotConfig>> // path -> properties (rotation, position, etc.)
  shelfConfig?: ShelfSchemaConfig
}

export interface SlotGroup {
  groupId: string
  name: string
  controlType: 'schema_select' | 'checkbox_group'
  controlledSlots: string[]
  schemas: Schema[]
  defaultSchemaId?: string
}

export interface FurnitureConfig {
  id: string
  name: string
  category: string
  componentSlots: ComponentSlotConfig[]
  slotGroups?: SlotGroup[]
  price?: number
  height?: number
  width?: number
  depth?: number
  dimensions?: {
    width: number
    height: number
    depth: number
  }
}

export interface ComponentDatabase {
  [key: string]: ComponentConfig[]
}

export interface GlobalSettingConfig {
  id: string
  name: string
  groupId: string // ÚJ
  type: 'material' | 'component' // MÓDOSÍTVA
  allowedMaterialCategories?: string[]
  allowedComponentIds?: string[] // ÚJ
  // targetSlotId és options mezők törölhetők, ha már nem használod a régi logikát
}

// --- STÍLUS DEFINÍCIÓ ---
export interface FurnitureStyle {
  id: string
  name: string
  description?: string
}

export interface StyleVariant {
  id: string
  name: string // Pl. "Keretes / Klasszikus"
  componentIds: string[] // Pl. ["front_keretes_60", "front_keretes_30", "drawer_keretes"]
}

export interface GlobalGroupConfig {
  id: string
  name: string // Pl. "Ajtók és Fiókok"
  targets: string[] // Pl. ["fronts", "drawers"] - Miket vezérel?

  // Anyag Beállítások
  material: {
    enabled: boolean
    allowedCategories: string[] // Pl. ["Bútorlap", "Festett"]
  }

  // Stílus Beállítások
  style: {
    enabled: boolean
    variants: StyleVariant[] // Itt vannak a csoportosított stílusok
  }

  // --- ÚJ: Slot-specifikus beállítások ---
  slots?: {
    key: string // pl. "glass"
    name: string // pl. "Üvegbetét"
    allowedCategories: string[] // pl. ["Üveg"]
  }[]

  construction?: {
    enabled: boolean
    // Lábakhoz (Range)
    minHeight?: number // méterben tároljuk
    maxHeight?: number // méterben tároljuk
    // Munkapulthoz (Lista) - ÚJ
    thicknessOptions?: number[] // méterben tároljuk (pl. [0.028, 0.038])
    defaultThickness?: number // méterben
  }
}

export interface MaterialConfig {
  id: string
  name: string
  category: string | string[]
  type: 'color' | 'texture'
  value: string
  properties?: {
    roughness?: number
    metalness?: number
    [key: string]: any
  }
}

export interface MaterialSlotDef {
  key: string // pl. "base", "glass", "handle"
  name: string // Megjelenő név, pl. "Keret", "Üveg"
  target: string // A GLB-ben lévő material neve (részlet), ami alapján megtaláljuk
  defaultMaterial?: string // Opcionális alapértelmezett anyag ID
  allowedCategories?: string[] // pl. ["Bútorlap", "Fa"] vagy ["Üveg"]
}

export interface GeneralSettings {
  upperCabinet: {
    defaultElevation: number
  }
}
